### ISSUE TITLE
Do poprawy

### ISSUE THREAD

**Issue by kacgrzes** [arkadiusz-cichosz/my-job#1]
- [x] popraw wcięcia w kodzie

Opcjonalnie:
- [x] przepisz kod `css` do formatu `sass/scss`
- [x] podziel stworzony plik sass/scss na mniejsze porcje. Wydziel grid'a, nawigację, sekcje oraz footer
- [x] stwórz plik `.gitignore`, a następnie dodaj co niego rzeczy, które nie powinny znaleźć się w repozytorium. W Twoim przypadku powinny się tutaj wskoczyć pliki `css` wygenerowane podczas procesu kompilacji. Dlaczego? Skoro można przeprowadzić kompilację kodu `sass/scss` uzyskując tym samym pliki `css` na komputerze osobistym to po co wrzucać je do repozytorium?

**Comment by arkadiusz-cichosz** [comment]
OKi, chyba teraz dobrze??

**Comment by kacgrzes** [comment]
wszystko spoko, tylko pliki powinny być w katalogu sass
